name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
  
    - name: Build
      env:
        PUBLIC_KEY: ${{ deploy.PUBLIC_KEY }}
        PRIVATE_KEY: ${{ deploy.PRIVATE_KEY }}
        POSTGRES_PASSWORD: ${{ deploy.POSTGRES_PASSWORD }}
      run: |+
        set -a
        source config.env.deploy
        set +a
        docker compose -f docker-compose-tests.yml up -d --build

    - name: Test
      env:
        PUBLIC_KEY: ${{ deploy.PUBLIC_KEY }}
        PRIVATE_KEY: ${{ deploy.PRIVATE_KEY }}
        POSTGRES_PASSWORD: ${{ deploy.POSTGRES_PASSWORD }}
      run: |+
        set -a
        source config.env.deploy
        set +a
        docker compose exec app go test ./tests/...

