name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
  
    - name: Build
      run: |+
        set -a
        source config.env.deploy
        set +a
        export PUBLIC_KEY=${{ deploy.PUBLIC_KEY }}
        export PRIVATE_KEY=${{ deploy.PRIVATE_KEY }}
        export POSTGRES_PASSWORD=${{ deploy.POSTGRES_PASSWORD }}
        docker compose -f docker-compose-tests.yml up -d --build

    - name: Test
      run: |+
        set -a
        source config.env.deploy
        set +a
        export PUBLIC_KEY=${{ deploy.PUBLIC_KEY }}
        export PRIVATE_KEY=${{ deploy.PRIVATE_KEY }}
        export POSTGRES_PASSWORD=${{ deploy.POSTGRES_PASSWORD }}
        docker compose exec app go test ./tests/...

