name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    environment: deploy    
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
  
    - name: Build
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |+
        set -a
        source config.env.deploy
        set +a
        docker compose -f docker-compose.yml up -d --build
        docker compose exec $POSTGRES_CONTAINER_NAME cat /docker-entrypoint-initdb.d/*.sql | psql -U $POSTGRES_DB -d $POSTGRES_USER

    - name: Wait
      run: ./scripts/wait-for-it.sh

    - name: Test
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |+
        set -a
        source config.env.deploy
        set +a
        docker compose exec $APP_CONTAINER_NAME go test ./tests/...

