name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    environment: deploy    
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
  
    - name: Build
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |+
        set -a
        source config.env.deploy
        set +a
        docker compose -f docker-compose-tests.yml up -d --build

    - name: Wait
      run: ./scripts/wait-for-it.sh

    - name: Test
      run: docker compose exec app go test ./tests/...

